services:
  postgres:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  django:
    container_name: django
    build: ./django
    volumes:
      - ./django:/usr/src/app
      - gunicorn-sock:/var/run/gunicorn
    environment:
      - DJANGO_SETTINGS_MODULE=myapp.settings.local
      - SECRET_KEY=$SECRET_KEY
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
    command: |
      bash -c "python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn myapp.wsgi --bind=unix:/var/run/gunicorn/gunicorn.sock"
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - gunicorn-sock:/var/run/gunicorn
      - ./django/static:/usr/share/static
volumes:
  gunicorn-sock:
  postgres-data:
