FROM nginx:1.25.4

# 設定ファイルの移動
RUN rm -f /etc/nginx/conf.d/*
COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d/django.conf /etc/nginx/conf.d/django.conf

VOLUME ["/var/run/gunicorn", "/usr/share/static"]
